import Link from "next/link";
import { ArrowLeft, Flame, Share2, ThumbsUp, ThumbsDown } from "lucide-react";

export default function RoastPage({ params }: { params: { id: string } }) {
  const [homeTeam, awayTeam] = params.id.toUpperCase().split("-VS-");

  return (
    <div className="min-h-screen pb-24 p-4 animate-slide-up pt-8">
      <Link href={`/predict/${params.id}`} className="text-gray-400 text-sm mb-6 inline-flex items-center gap-1">
        <ArrowLeft className="w-4 h-4" /> Back to Match
      </Link>
      
      <div className="mb-8">
        <h1 className="text-3xl font-black flex items-center gap-2">
          AI POST-MATCH VERDICT <Flame className="w-8 h-8 text-primary" />
        </h1>
        <p className="text-gray-400 text-sm mt-2">Savage roasts and epic praise generated by AI after every match.</p>
      </div>

      {/* Roast Section */}
      <div className="bg-red-950/30 border border-red-500/30 rounded-3xl p-6 relative overflow-hidden mb-6">
        <div className="absolute -top-10 -right-10 w-32 h-32 bg-red-500/20 blur-3xl rounded-full" />
        <h2 className="text-red-400 font-bold mb-4 flex items-center gap-2">
          <Flame className="w-5 h-5" /> ROAST OF THE DAY
        </h2>
        
        <div className="bg-black/50 p-4 rounded-2xl border border-red-500/20 mb-4">
          <p className="text-lg font-medium text-gray-200 leading-relaxed italic">
            "Bro played a beautiful test match innings of 22(28) in a T20 chase of 200. The only thing he successfully chased was his spot back to the pavilion."
          </p>
          <div className="mt-4 flex items-center gap-3">
            <div className="w-10 h-10 bg-card-bg rounded-full flex items-center justify-center border border-border">😢</div>
            <div>
              <p className="font-bold text-sm">Target Player</p>
              <p className="text-xs text-red-400 font-bold">Worst Performer</p>
            </div>
          </div>
        </div>

        <div className="flex justify-between items-center mt-4 border-t border-red-500/20 pt-4">
          <div className="flex gap-4">
            <button className="flex items-center gap-1 text-gray-400 hover:text-white transition-colors">
              <ThumbsUp className="w-5 h-5" /> <span className="text-xs font-bold">4.2K</span>
            </button>
            <button className="flex items-center gap-1 text-gray-400 hover:text-white transition-colors">
              <ThumbsDown className="w-5 h-5" /> <span className="text-xs font-bold">112</span>
            </button>
          </div>
          <button 
            onClick={() => {
              const text = `Bro played a beautiful test match innings of 22(28) in a T20 chase of 200. The only thing he successfully chased was his spot back to the pavilion. 😂🔥 \n\nCheck out more savage AI roasts on CricketIQ: https://cricketiq.in/predict/${params.id}/roast`;
              if (navigator.share) {
                navigator.share({ title: 'AI Cricket Roast', text });
              } else {
                window.open(`https://wa.me/?text=${encodeURIComponent(text)}`);
              }
            }}
            className="flex items-center gap-2 text-sm font-bold bg-[#25D366] text-white px-4 py-2 rounded-xl hover:scale-105 transition-transform"
          >
            <Share2 className="w-4 h-4" /> Share
          </button>
        </div>
      </div>

      {/* Praise Section */}
      <div className="bg-green-950/30 border border-green-500/30 rounded-3xl p-6 relative overflow-hidden">
        <div className="absolute -top-10 -right-10 w-32 h-32 bg-green-500/20 blur-3xl rounded-full" />
        <h2 className="text-green-400 font-bold mb-4 flex items-center gap-2">
          ⭐ EPIC PRAISE
        </h2>
        
        <div className="bg-black/50 p-4 rounded-2xl border border-green-500/20 mb-4">
          <p className="text-lg font-medium text-gray-200 leading-relaxed italic">
            "An absolute masterclass! He didn't just hit the ball; he sent it to a different pin code. Bowlers will be seeing him in their nightmares tonight."
          </p>
          <div className="mt-4 flex items-center gap-3">
            <div className="w-10 h-10 bg-card-bg rounded-full flex items-center justify-center border border-border">👑</div>
            <div>
              <p className="font-bold text-sm">Star Player</p>
              <p className="text-xs text-green-400 font-bold">Man of the Match</p>
            </div>
          </div>
        </div>

        <div className="flex justify-between items-center mt-4 border-t border-green-500/20 pt-4">
          <div className="flex gap-4">
            <button className="flex items-center gap-1 text-gray-400 hover:text-white transition-colors">
              <ThumbsUp className="w-5 h-5 text-green-400" /> <span className="text-xs font-bold text-green-400">12.5K</span>
            </button>
          </div>
          <button 
            onClick={() => {
              const text = `An absolute masterclass! He didn't just hit the ball; he sent it to a different pin code. Bowlers will be seeing him in their nightmares tonight. 👑🏏 \n\nSee more AI analysis on CricketIQ: https://cricketiq.in/predict/${params.id}/roast`;
              if (navigator.share) {
                navigator.share({ title: 'AI Match Praise', text });
              } else {
                window.open(`https://wa.me/?text=${encodeURIComponent(text)}`);
              }
            }}
            className="flex items-center gap-2 text-sm font-bold bg-[#25D366] text-white px-4 py-2 rounded-xl hover:scale-105 transition-transform"
          >
            <Share2 className="w-4 h-4" /> Share
          </button>
        </div>
      </div>
    </div>
  );
}
